// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as RoutesXrayAPI from "./routesxrayapi.js";
import * as RunXrayCore from "./runxraycore.js";
export {
    RoutesXrayAPI,
    RunXrayCore
};
