// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @param {boolean} updateActiveVPN
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Kill(updateActiveVPN) {
    let $resultPromise = /** @type {any} */($Call.ByID(1733052041, updateActiveVPN));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Run() {
    let $resultPromise = /** @type {any} */($Call.ByID(2121787930));
    return $resultPromise;
}
