// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * @returns {Promise<models$0.Config> & { cancel(): void }}
 */
export function GetConfig() {
    let $resultPromise = /** @type {any} */($Call.ByID(2668193461));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {boolean} activeVPN
 * @returns {Promise<void> & { cancel(): void }}
 */
export function UpdateActiveVPN(activeVPN) {
    let $resultPromise = /** @type {any} */($Call.ByID(791720730, activeVPN));
    return $resultPromise;
}

/**
 * @param {boolean} disableRoutes
 * @returns {Promise<void> & { cancel(): void }}
 */
export function UpdateDisableRoutes(disableRoutes) {
    let $resultPromise = /** @type {any} */($Call.ByID(4228344106, disableRoutes));
    return $resultPromise;
}

/**
 * @param {string} listMode
 * @returns {Promise<void> & { cancel(): void }}
 */
export function UpdateListMode(listMode) {
    let $resultPromise = /** @type {any} */($Call.ByID(2547500639, listMode));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = models$0.Config.createFrom;
