// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ConfigRepository from "./configrepository.js";
import * as RoutesRepository from "./routesrepository.js";
import * as SettingsRepository from "./settingsrepository.js";
export {
    ConfigRepository,
    RoutesRepository,
    SettingsRepository
};
