// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as RoutesXrayAPI from "./routesxrayapi.js";
import * as RunXrayAPI from "./runxrayapi.js";
export {
    RoutesXrayAPI,
    RunXrayAPI
};
