// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ActualizeConfig() {
    let $resultPromise = /** @type {any} */($Call.ByID(3640805118));
    return $resultPromise;
}

/**
 * @param {string} listMode
 * @param {string} domain
 * @returns {Promise<void> & { cancel(): void }}
 */
export function AddDomain(listMode, domain) {
    let $resultPromise = /** @type {any} */($Call.ByID(832789031, listMode, domain));
    return $resultPromise;
}

/**
 * @param {string} listMode
 * @param {string} ip
 * @returns {Promise<void> & { cancel(): void }}
 */
export function AddIP(listMode, ip) {
    let $resultPromise = /** @type {any} */($Call.ByID(1229227802, listMode, ip));
    return $resultPromise;
}

/**
 * @param {string} listMode
 * @param {string} port
 * @returns {Promise<void> & { cancel(): void }}
 */
export function AddPort(listMode, port) {
    let $resultPromise = /** @type {any} */($Call.ByID(1045494412, listMode, port));
    return $resultPromise;
}

/**
 * @param {string} listMode
 * @param {string} domain
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DelDomain(listMode, domain) {
    let $resultPromise = /** @type {any} */($Call.ByID(866825505, listMode, domain));
    return $resultPromise;
}

/**
 * @param {string} listMode
 * @param {string} ip
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DelIP(listMode, ip) {
    let $resultPromise = /** @type {any} */($Call.ByID(4204939916, listMode, ip));
    return $resultPromise;
}

/**
 * @param {string} listMode
 * @param {string} port
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DelPort(listMode, port) {
    let $resultPromise = /** @type {any} */($Call.ByID(241446454, listMode, port));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DisableBlackList() {
    let $resultPromise = /** @type {any} */($Call.ByID(37194071));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DisableRoutes() {
    let $resultPromise = /** @type {any} */($Call.ByID(647638950));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function EnableBlackList() {
    let $resultPromise = /** @type {any} */($Call.ByID(3260102114));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function EnableRoutes() {
    let $resultPromise = /** @type {any} */($Call.ByID(2354769125));
    return $resultPromise;
}

/**
 * @param {string} listMode
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetDomain(listMode) {
    let $resultPromise = /** @type {any} */($Call.ByID(329915160, listMode));
    return $resultPromise;
}

/**
 * @param {string} listMode
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetIP(listMode) {
    let $resultPromise = /** @type {any} */($Call.ByID(1415065821, listMode));
    return $resultPromise;
}

/**
 * @param {string} listMode
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetPort(listMode) {
    let $resultPromise = /** @type {any} */($Call.ByID(849224487, listMode));
    return $resultPromise;
}

/**
 * @param {models$0.OutboundConfig[] | null} outbounds
 * @param {string} tag1
 * @param {string} tag2
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SwapOutbounds(outbounds, tag1, tag2) {
    let $resultPromise = /** @type {any} */($Call.ByID(3672520520, outbounds, tag1, tag2));
    return $resultPromise;
}
