// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Kill() {
    let $resultPromise = /** @type {any} */($Call.ByID(4143057079));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function KillOnClose() {
    let $resultPromise = /** @type {any} */($Call.ByID(3078502926));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Run() {
    let $resultPromise = /** @type {any} */($Call.ByID(2967603648));
    return $resultPromise;
}
