// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['repository']['ConfigRepository']['GetConfig']();
}

export function UpdateActiveVPN(arg1) {
  return window['go']['repository']['ConfigRepository']['UpdateActiveVPN'](arg1);
}

export function UpdateDisableRoutes(arg1) {
  return window['go']['repository']['ConfigRepository']['UpdateDisableRoutes'](arg1);
}

export function UpdateListMode(arg1) {
  return window['go']['repository']['ConfigRepository']['UpdateListMode'](arg1);
}
