// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetConfig():Promise<models.Config>;

export function UpdateActiveVPN(arg1:boolean):Promise<void>;

export function UpdateDisableRoutes(arg1:boolean):Promise<void>;

export function UpdateListMode(arg1:string):Promise<void>;
