// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddRule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteRule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetRoutes(arg1:string):Promise<models.ListConfig>;
