// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1, arg2, arg3) {
  return window['go']['repository']['RoutesRepository']['AddRule'](arg1, arg2, arg3);
}

export function DeleteRule(arg1, arg2, arg3) {
  return window['go']['repository']['RoutesRepository']['DeleteRule'](arg1, arg2, arg3);
}

export function GetRoutes(arg1) {
  return window['go']['repository']['RoutesRepository']['GetRoutes'](arg1);
}
