// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Hide() {
    let $resultPromise = /** @type {any} */($Call.ByID(1726004904));
    return $resultPromise;
}

/**
 * @returns {Promise<boolean> & { cancel(): void }}
 */
export function IsGOOSWindows() {
    let $resultPromise = /** @type {any} */($Call.ByID(566006509));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Show() {
    let $resultPromise = /** @type {any} */($Call.ByID(2391431329));
    return $resultPromise;
}
