// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {models} from '../models';

export function GetJSON():Promise<config.StructJSON>;

export function GetXray():Promise<models.Xray>;
