// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetJSON() {
  return window['go']['config']['Config']['GetJSON']();
}

export function GetXray() {
  return window['go']['config']['Config']['GetXray']();
}
