// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as io$0 from "../../../../io/models.js";

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function CaptureTraffic() {
    let $resultPromise = /** @type {any} */($Call.ByID(4085566562));
    return $resultPromise;
}

/**
 * @param {string} typeTraffic
 * @param {string} typeChannel
 * @returns {Promise<number> & { cancel(): void }}
 */
export function GetTraffic(typeTraffic, typeChannel) {
    let $resultPromise = /** @type {any} */($Call.ByID(4122408772, typeTraffic, typeChannel));
    return $resultPromise;
}

/**
 * @param {io$0.ReadCloser} stdoutPipe
 * @returns {Promise<string> & { cancel(): void }}
 */
export function ScannerStdout(stdoutPipe) {
    let $resultPromise = /** @type {any} */($Call.ByID(2482824854, stdoutPipe));
    return $resultPromise;
}
