// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {io} from '../models';

export function CaptureTraffic():Promise<void>;

export function GetTraffic(arg1:string,arg2:string):Promise<number>;

export function ScannerStdout(arg1:io.ReadCloser):Promise<string>;
