// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureTraffic() {
  return window['go']['stats']['Traffic']['CaptureTraffic']();
}

export function GetTraffic(arg1, arg2) {
  return window['go']['stats']['Traffic']['GetTraffic'](arg1, arg2);
}

export function ScannerStdout(arg1) {
  return window['go']['stats']['Traffic']['ScannerStdout'](arg1);
}
