// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActualizeConfig() {
  return window['go']['xray_api']['RoutesXrayAPI']['ActualizeConfig']();
}

export function AddDomain(arg1, arg2) {
  return window['go']['xray_api']['RoutesXrayAPI']['AddDomain'](arg1, arg2);
}

export function AddIP(arg1, arg2) {
  return window['go']['xray_api']['RoutesXrayAPI']['AddIP'](arg1, arg2);
}

export function AddPort(arg1, arg2) {
  return window['go']['xray_api']['RoutesXrayAPI']['AddPort'](arg1, arg2);
}

export function DelDomain(arg1, arg2) {
  return window['go']['xray_api']['RoutesXrayAPI']['DelDomain'](arg1, arg2);
}

export function DelIP(arg1, arg2) {
  return window['go']['xray_api']['RoutesXrayAPI']['DelIP'](arg1, arg2);
}

export function DelPort(arg1, arg2) {
  return window['go']['xray_api']['RoutesXrayAPI']['DelPort'](arg1, arg2);
}

export function DisableBlackList() {
  return window['go']['xray_api']['RoutesXrayAPI']['DisableBlackList']();
}

export function DisableRoutes() {
  return window['go']['xray_api']['RoutesXrayAPI']['DisableRoutes']();
}

export function EnableBlackList() {
  return window['go']['xray_api']['RoutesXrayAPI']['EnableBlackList']();
}

export function EnableRoutes() {
  return window['go']['xray_api']['RoutesXrayAPI']['EnableRoutes']();
}

export function GetDomain(arg1) {
  return window['go']['xray_api']['RoutesXrayAPI']['GetDomain'](arg1);
}

export function GetIP(arg1) {
  return window['go']['xray_api']['RoutesXrayAPI']['GetIP'](arg1);
}

export function GetPort(arg1) {
  return window['go']['xray_api']['RoutesXrayAPI']['GetPort'](arg1);
}

export function SwapOutbounds(arg1, arg2, arg3) {
  return window['go']['xray_api']['RoutesXrayAPI']['SwapOutbounds'](arg1, arg2, arg3);
}
