// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Kill() {
  return window['go']['xray_api']['RunXrayAPI']['Kill']();
}

export function Run() {
  return window['go']['xray_api']['RunXrayAPI']['Run']();
}
