// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Kill():Promise<void>;

export function KillOnClose():Promise<void>;

export function Run():Promise<void>;
