// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDomain(arg1, arg2) {
  return window['go']['xray_api']['XrayAPI']['AddDomain'](arg1, arg2);
}

export function AddIP(arg1, arg2) {
  return window['go']['xray_api']['XrayAPI']['AddIP'](arg1, arg2);
}

export function AddPort(arg1, arg2) {
  return window['go']['xray_api']['XrayAPI']['AddPort'](arg1, arg2);
}

export function DelDomain(arg1, arg2) {
  return window['go']['xray_api']['XrayAPI']['DelDomain'](arg1, arg2);
}

export function DelIP(arg1, arg2) {
  return window['go']['xray_api']['XrayAPI']['DelIP'](arg1, arg2);
}

export function DelPort(arg1, arg2) {
  return window['go']['xray_api']['XrayAPI']['DelPort'](arg1, arg2);
}

export function DisableRoutes() {
  return window['go']['xray_api']['XrayAPI']['DisableRoutes']();
}

export function EnableRoutes() {
  return window['go']['xray_api']['XrayAPI']['EnableRoutes']();
}

export function GetDomain(arg1) {
  return window['go']['xray_api']['XrayAPI']['GetDomain'](arg1);
}

export function GetIP(arg1) {
  return window['go']['xray_api']['XrayAPI']['GetIP'](arg1);
}

export function GetPort(arg1) {
  return window['go']['xray_api']['XrayAPI']['GetPort'](arg1);
}

export function Kill() {
  return window['go']['xray_api']['XrayAPI']['Kill']();
}

export function Run() {
  return window['go']['xray_api']['XrayAPI']['Run']();
}

export function SwapOutbounds(arg1, arg2, arg3) {
  return window['go']['xray_api']['XrayAPI']['SwapOutbounds'](arg1, arg2, arg3);
}
