// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDomain(arg1:string,arg2:string):Promise<void>;

export function AddIP(arg1:string,arg2:string):Promise<void>;

export function AddPort(arg1:string,arg2:string):Promise<void>;

export function DelDomain(arg1:string,arg2:string):Promise<void>;

export function DelIP(arg1:string,arg2:string):Promise<void>;

export function DelPort(arg1:string,arg2:string):Promise<void>;

export function DisableRoutes():Promise<void>;

export function EnableRoutes():Promise<void>;

export function GetDomain(arg1:string):Promise<string>;

export function GetIP(arg1:string):Promise<string>;

export function GetPort(arg1:string):Promise<string>;

export function Kill():Promise<boolean>;

export function Run():Promise<boolean>;

export function SwapOutbounds(arg1:any,arg2:string,arg3:string):Promise<void>;
