// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureStdout() {
  return window['go']['log']['Log']['CaptureStdout']();
}

export function GetLogs() {
  return window['go']['log']['Log']['GetLogs']();
}
