name: SLSA Go releaser
on:
  push:
    tags:
      - '*'
  workflow_dispatch: 

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: vpngui-linux-amd64
            platform: linux/amd64
            os: ubuntu-latest
          - name: vpngui-linux-arm64
            platform: linux/arm64
            os: ubuntu-latest
          - name: vpngui-windows-amd64
            platform: windows/amd64
            os: windows-latest
          - name: vpngui-windows-arm64
            platform: windows/arm64
            os: windows-latest
          - name: vpngui-darwin-amd64
            platform: darwin/amd64
            os: macos-latest
          - name: vpngui-darwin-arm64
            platform: darwin/arm64
            os: macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: npm install

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.name }}
          build-platform: ${{ matrix.platform }}
          package: true
          go-version: '1.23'

