name: SLSA Go releaser
on:
  push:
    tags:
      - '*'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name: ['App']
        platform: ['linux/amd64', 'linux/arm64', 'windows/amd64', 'windows/arm64', 'darwin/amd64', 'darwin/arm64']
        os: ['ubuntu-latest', 'ubuntu-latest', 'windows-latest', 'windows-latest', 'macos-latest', 'macos-latest']

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.name }}
          build-platform: ${{ matrix.platform }}
          package: false
          go-version: '1.23'

